### ISSUE TITLE
self.attacked_model.train() leads to autograd error

### ISSUE THREAD

**Issue by nixror** [sigeisler/robustness_of_gnns_at_scale#4]
Hi, thanks for your solid work！
I want to change the loss function, which requires setting self.attacked_model.train() in prbcd.py （ I haven't changed anywhere else.）
However, this will cause the backward function in utils.grad_with_checkpoint to report an error:

"RuntimeError: Trying to backward through the graph a second time..."

Set retain_graph in backward() to True, then the grad of self.perturbed_edge_weight after backward() is None.
I've been confused about this bug for a long time, could you please help me?

**Comment by sigeisler** [comment]
I haven't tried setting `train`. Spontaneously I would suggest switching off caching [here](https://github.com/sigeisler/robustness_of_gnns_at_scale/blob/0f4844711ace599f54c2abc760b53680a80d6a32/rgnn_at_scale/models/gcn.py#L143).

If this does not resolve your issue, I would appreciate if you could generate a minimal example or explain how to reproduce the error (e.g. what code to insert where).

**Comment by nixror** [comment]
Thanks for your suggestion!
You saved me!!!
